### ISSUE TITLE
Include Discord's Message Content Intent instruction to README

### ISSUE THREAD

**Issue by sullyvannunes** [ajivoin/tug-of-war#68]
I am new to Discord's bot world and when I was running this bot on my server I got the following error message 
```
~/tug-of-war/node_modules/discord.js/src/client/websocket/WebSocketManager.js:250
        throw new Error(unrecoverableErrorCodeMap[error.code]);
              ^

Error [DisallowedIntents]: Privileged intent provided is not enabled or whitelisted.
    at WebSocketManager.createShards (~//tug-of-war/node_modules/discord.js/src/client/websocket/WebSocketManager.js:250:15)
    at async Client.login (~/tug-of-war/node_modules/discord.js/src/client/Client.js:232:7) {
  code: 'DisallowedIntents'
}
```
Reading about [privileged intents](https://discordjs.guide/popular-topics/intents.html#privileged-intents) I got I needed to enable `Message Content Intent` on bot page. Do you believe it is better to add this info on README? May I open a pull request adding it?

**Comment by ajivoin** [comment]
Go ahead and add a PR for it :) I forgot to update documentation when I moved to discord.js 14
